/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["HealthController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowController_listStudents"];
        put?: never;
        post: operations["WorkflowController_createStudent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowController_student"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["WorkflowController_updateStudent"];
        trace?: never;
    };
    "/api/students/{id}/communications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowController_communications"];
        put?: never;
        post: operations["WorkflowController_communicate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/students/{id}/trial-eligibility": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowController_eligibility"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowController_sessions"];
        put?: never;
        post: operations["WorkflowController_createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowController_options"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["WorkflowController_updateSession"];
        trace?: never;
    };
    "/api/sessions/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorkflowController_cancelSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}/participants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowController_roster"];
        put?: never;
        post: operations["WorkflowController_add"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/participants/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorkflowController_cancel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/participants/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorkflowController_restore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/participants/{id}/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorkflowController_move"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}/changes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowController_changes"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorkflowController_feedback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowController_listTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["WorkflowController_task"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/follow-up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorkflowController_followUp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorkflowController_reopen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{id}/suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["WorkflowController_suggest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthDto: {
            status: string;
            timezone: string;
            database: string;
        };
        LoginDto: {
            /** @example alice@example.com */
            email: string;
            password: string;
        };
        UserDto: {
            id: string;
            name: string;
            email: string;
            /** @enum {string} */
            role: "ADMIN" | "TEACHER";
        };
        AuthDto: {
            user: components["schemas"]["UserDto"];
            csrfToken: string;
        };
        LogoutDto: {
            ok: boolean;
        };
        StudentDto: {
            id: string;
            name: string;
            yearLevel: string;
        };
        StudentPageDto: {
            items: components["schemas"]["StudentDto"][];
            total: number;
            page: number;
            pageSize: number;
        };
        CreateStudentDto: {
            guardianName?: string;
            guardianRelationship?: string;
            guardianPhone?: string;
            guardianEmail?: string;
            guardianWechat?: string;
            /** @enum {string} */
            preferredChannel?: "" | "EMAIL" | "PHONE" | "SMS" | "WECHAT";
            /** @enum {string} */
            preferredLanguage?: "en-AU" | "zh-CN";
            learningGoals?: string;
            preferredTimes?: string;
            interestedSubjects?: string;
            /** @example 2026-09-17 */
            firstEnrolledOn?: string;
            name: string;
            /** @enum {string} */
            yearLevel: "Foundation" | "Year 1" | "Year 2" | "Year 3" | "Year 4" | "Year 5" | "Year 6" | "Year 7" | "Year 8" | "Year 9" | "Year 10" | "Year 11" | "Year 12" | "Not assessed";
        };
        LessonDto: {
            id: string;
            className: string;
            classGroupId: string;
            targetLevel: string;
            courseId: string;
            courseName: string;
            teacherName: string;
            teacherId: string;
            startsAt: string;
            endsAt: string;
            capacity: number;
            participantCount: number;
            trialCount: number;
            newCount: number;
            status: string;
            version: number;
            feedbackSubmittedAt: string | null;
            summary: string | null;
        };
        TeachingRecordDto: {
            participantId: string;
            lesson: components["schemas"]["LessonDto"];
            attendance: string;
            feedback: string | null;
        };
        StudentDetailDto: {
            id: string;
            name: string;
            yearLevel: string;
            canEdit: boolean;
            version: number;
            firstEnrolledOn: string | null;
            guardianName?: string;
            guardianRelationship?: string;
            guardianPhone?: string;
            guardianEmail?: string;
            guardianWechat?: string;
            preferredChannel?: string;
            preferredLanguage?: string;
            learningGoals?: string;
            preferredTimes?: string;
            interestedSubjects?: string;
            teachingRecords: components["schemas"]["TeachingRecordDto"][];
        };
        UpdateStudentDto: {
            guardianName?: string;
            guardianRelationship?: string;
            guardianPhone?: string;
            guardianEmail?: string;
            guardianWechat?: string;
            /** @enum {string} */
            preferredChannel?: "" | "EMAIL" | "PHONE" | "SMS" | "WECHAT";
            /** @enum {string} */
            preferredLanguage?: "en-AU" | "zh-CN";
            learningGoals?: string;
            preferredTimes?: string;
            interestedSubjects?: string;
            /** @example 2026-09-17 */
            firstEnrolledOn?: string;
            name?: string;
            /** @enum {string} */
            yearLevel?: "Foundation" | "Year 1" | "Year 2" | "Year 3" | "Year 4" | "Year 5" | "Year 6" | "Year 7" | "Year 8" | "Year 9" | "Year 10" | "Year 11" | "Year 12" | "Not assessed";
            expectedVersion: number;
        };
        ActionDto: {
            id: string;
        };
        CommunicationViewDto: {
            id: string;
            studentId: string;
            guardianNameSnapshot: string;
            channel: string;
            content: string;
            occurredAt: string;
            authorName: string;
            outcome: string | null;
        };
        CommunicationPageDto: {
            items: components["schemas"]["CommunicationViewDto"][];
            total: number;
            page: number;
            pageSize: number;
        };
        CommunicationDto: {
            guardianNameSnapshot: string;
            relationshipSnapshot?: string;
            /** @enum {string} */
            channel: "EMAIL" | "PHONE" | "SMS" | "WECHAT" | "IN_PERSON";
            content: string;
            occurredAt: string;
            taskId?: string;
            participantId?: string;
        };
        EligibilityDto: {
            remaining: number;
            available: number;
            reason: string | null;
        };
        NamedOptionDto: {
            id: string;
            name: string;
        };
        SessionOptionsDto: {
            classes: components["schemas"]["NamedOptionDto"][];
            courses: components["schemas"]["NamedOptionDto"][];
            teachers: components["schemas"]["NamedOptionDto"][];
        };
        CreateSessionDto: {
            classGroupId: string;
            courseId: string;
            teacherId: string;
            startsAt: string;
            endsAt: string;
            capacity: number;
        };
        UpdateSessionDto: {
            classGroupId?: string;
            courseId?: string;
            teacherId?: string;
            startsAt?: string;
            endsAt?: string;
            capacity?: number;
            expectedVersion: number;
            reason: string;
            confirmedAffectedParticipantIds: string[];
        };
        CancelSessionDto: {
            expectedVersion: number;
            reason: string;
            confirmedAffectedParticipantIds: string[];
        };
        ParticipantDto: {
            id: string;
            name: string;
            yearLevel: string;
            participantId: string;
            kind: string;
            category: string;
            bookingStatus: string;
            attendance: string;
            version: number;
            canManage: boolean;
            feedback: string | null;
            abilityNote: string | null;
            preferenceNote: string | null;
        };
        RosterDto: {
            lesson: components["schemas"]["LessonDto"];
            participants: components["schemas"]["ParticipantDto"][];
            cancelled: components["schemas"]["ParticipantDto"][];
        };
        AddParticipantDto: {
            studentId: string;
            /** @enum {string} */
            kind: "TRIAL" | "REGULAR";
        };
        VersionDto: {
            expectedVersion: number;
            reason: string;
        };
        MoveParticipantDto: {
            expectedVersion: number;
            reason: string;
            targetSessionId: string;
        };
        ChangeDto: {
            id: string;
            action: string;
            reason: string;
            actorName: string;
            createdAt: string;
            before: string;
            after: string;
        };
        ChangePageDto: {
            items: components["schemas"]["ChangeDto"][];
            total: number;
            page: number;
            pageSize: number;
        };
        FeedbackItemDto: {
            participantId: string;
            /** @enum {string} */
            attendance: "ATTENDED" | "NO_SHOW";
            feedback?: string;
            abilityNote?: string;
            preferenceNote?: string;
        };
        FeedbackDto: {
            expectedVersion: number;
            summary?: string;
            students: components["schemas"]["FeedbackItemDto"][];
        };
        TaskDto: {
            id: string;
            type: string;
            status: string;
            version: number;
            sessionId: string;
            participantId: string | null;
            reason: string | null;
            availableAt: string;
            dueAt: string;
            className: string;
            courseName: string;
            teacherName: string;
            startsAt: string;
            endsAt: string;
            studentId: string | null;
            studentName: string | null;
        };
        TaskPageDto: {
            items: components["schemas"]["TaskDto"][];
            total: number;
            page: number;
            pageSize: number;
        };
        TaskDetailDto: {
            id: string;
            type: string;
            status: string;
            version: number;
            sessionId: string;
            participantId: string | null;
            reason: string | null;
            availableAt: string;
            dueAt: string;
            className: string;
            courseName: string;
            teacherName: string;
            startsAt: string;
            endsAt: string;
            studentId: string | null;
            studentName: string | null;
            lesson: components["schemas"]["LessonDto"];
            student: components["schemas"]["StudentDetailDto"] | null;
            participant: components["schemas"]["ParticipantDto"] | null;
        };
        FollowUpDto: {
            expectedVersion: number;
            communication: components["schemas"]["CommunicationDto"];
            /** @enum {string} */
            outcome: "NO_ANSWER" | "CONSIDERING" | "INTERESTED" | "NOT_INTERESTED" | "ENROLLED";
            nextDueAt?: string;
            closeReason?: string;
            firstEnrolledOn?: string;
        };
        ReopenDto: {
            expectedVersion: number;
            reason: string;
            nextDueAt: string;
        };
        SuggestionRequest: {
            /** @enum {string} */
            channel: "EMAIL" | "PHONE" | "SMS" | "WECHAT" | "IN_PERSON";
            /** @enum {string} */
            language: "en-AU" | "zh-CN";
        };
        ObservationDto: {
            text: string;
            sourceIds: string[];
        };
        EvidenceDto: {
            id: string;
            text: string;
        };
        SuggestionDto: {
            summary: string;
            observations: components["schemas"]["ObservationDto"][];
            questions: string[];
            suggestedNextStep: string;
            talkingPoints: string[];
            subject: string | null;
            messageDraft: string | null;
            source: string;
            generatedAt: string;
            inputRecordIds: string[];
            evidence: components["schemas"]["EvidenceDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthDto"];
                };
            };
        };
    };
    AuthController_login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthDto"];
                };
            };
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthDto"];
                };
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutDto"];
                };
            };
        };
    };
    WorkflowController_listStudents: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                q?: string;
                mine?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentPageDto"];
                };
            };
        };
    };
    WorkflowController_createStudent: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID retained when retrying identical input. */
                "idempotency-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStudentDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentDto"];
                };
            };
        };
    };
    WorkflowController_student: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentDetailDto"];
                };
            };
        };
    };
    WorkflowController_updateStudent: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID retained when retrying identical input. */
                "idempotency-key": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStudentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionDto"];
                };
            };
        };
    };
    WorkflowController_communications: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                q?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommunicationPageDto"];
                };
            };
        };
    };
    WorkflowController_communicate: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID retained when retrying identical input. */
                "idempotency-key": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CommunicationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionDto"];
                };
            };
        };
    };
    WorkflowController_eligibility: {
        parameters: {
            query: {
                courseId: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EligibilityDto"];
                };
            };
        };
    };
    WorkflowController_sessions: {
        parameters: {
            query: {
                week: string;
                q?: string;
                classGroupId?: string;
                courseId?: string;
                teacherId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonDto"][];
                };
            };
        };
    };
    WorkflowController_createSession: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID retained when retrying identical input. */
                "idempotency-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionDto"];
                };
            };
        };
    };
    WorkflowController_options: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionOptionsDto"];
                };
            };
        };
    };
    WorkflowController_updateSession: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID retained when retrying identical input. */
                "idempotency-key": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSessionDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionDto"];
                };
            };
        };
    };
    WorkflowController_cancelSession: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID retained when retrying identical input. */
                "idempotency-key": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CancelSessionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionDto"];
                };
            };
        };
    };
    WorkflowController_roster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterDto"];
                };
            };
        };
    };
    WorkflowController_add: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID retained when retrying identical input. */
                "idempotency-key": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddParticipantDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionDto"];
                };
            };
        };
    };
    WorkflowController_cancel: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID retained when retrying identical input. */
                "idempotency-key": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionDto"];
                };
            };
        };
    };
    WorkflowController_restore: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID retained when retrying identical input. */
                "idempotency-key": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VersionDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionDto"];
                };
            };
        };
    };
    WorkflowController_move: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID retained when retrying identical input. */
                "idempotency-key": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveParticipantDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionDto"];
                };
            };
        };
    };
    WorkflowController_changes: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                q?: string;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChangePageDto"];
                };
            };
        };
    };
    WorkflowController_feedback: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID retained when retrying identical input. */
                "idempotency-key": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionDto"];
                };
            };
        };
    };
    WorkflowController_listTasks: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                q?: string;
                status?: "OPEN" | "DONE" | "CANCELLED";
                type?: "LESSON_FEEDBACK" | "TRIAL_FOLLOWUP";
                overdue?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskPageDto"];
                };
            };
        };
    };
    WorkflowController_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDetailDto"];
                };
            };
        };
    };
    WorkflowController_followUp: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID retained when retrying identical input. */
                "idempotency-key": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FollowUpDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionDto"];
                };
            };
        };
    };
    WorkflowController_reopen: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID retained when retrying identical input. */
                "idempotency-key": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReopenDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionDto"];
                };
            };
        };
    };
    WorkflowController_suggest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SuggestionRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SuggestionDto"];
                };
            };
        };
    };
}
